#+TITLE: Editing Notes
#+AUTHOR: Adam Sherwood
#+EMAIL: theherk@gmail.com
#+DESCRIPTION: Reminders to myself about editing.

* Editing
+ Set individal file coding with: ~-*- coding: utf-8 -*-~.
+ Reset a buffer with coding: =revert-buffer-with-coding-system=.
+ selective-display =C-3 C-x $=
+ =C-z= to switch emacs/vim modes
+ select task status: =SPC m t=
+ edit link - =C-c C-l=
+ permanent search results - =C-c C-o=
+ last search - =spc '=
+ insert src - ~<s <tab>~

** align

Align things like trailing comments with =align-regexp=.

before:
#+begin_src yaml
- thing # This is a short thing.
- aLongerThing # This is a long thing.
#+end_src

after =M-x align-regexp # RET:
#+begin_src yaml
- thing        # This is a short thing.
- aLongerThing # This is a long thing.
#+end_src

** multi-edit
1. initiate a search with =SPC /= =Z Z=
2. enter in edit mode with =C-c C-e=
3. go to the occurrence and enter in iedit state with =SPC s e=
4. edit the occurrences then leave the iedit state
5. press =C-c C-c=

** tramp

Open files with local root the easy way: ~SPC f f~ then =/sudo::/=.

* org-mode

Set startup options with directive =STARTUP=. [[https://orgmode.org/manual/In_002dbuffer-Settings.html][Buffer Settings]]

#+begin_src org
#+STARTUP: overview
#+end_src

Each tree can have its visibility set individually using the =VISIBILITY= property.[[https://orgmode.org/manual/Initial-visibility.html][ Initial Visibility]]

#+begin_src org
:PROPERTIES:
:VISIBILITY: children
:END:
#+end_src

Open the agenda with =SPC o A=. You can show all tasks from there, but you can also expose only tasks in the current org file using =SPC t o t=.

Archive todo entries with =SPC m A=. You can move archive entries the archive file back back out using =org-refile= or =SPC m s r=
* python-mode

Use direnv for best venv, virtualenv, pyenv handling. Add the following:

#+begin_src rc
source_up
export AWS_PROFILE=maybe
layout pyenv 3.8.10
#+end_src

This will automatically create a virtual environment with the given python executable.

Remember to run =lsp-workspace-restart=.

* Just handy commands

+ window-enlargen: =SPC w o=, amazing and works in popups
+ balance-windows: =SPC w ==, set things back to even

* Make help

#+begin_src makefile
help: ## show help message
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m\033[0m\n"} /^[$$()% a-zA-Z./_-]+:.*?##/ { printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)
#+end_src


* AWS envrc

These commands are examples of how to run through state directories and create .envrc files.

#+begin_src shell
for d in $(find . -type d -name "dev*"); do echo "source_up\nexport AWS_PROFILE=cpp-$(basename $d)" > ${d}/.envrc; done
for d in $(find . -type d -name "dev*"); do direnv allow $d; done
for d in $(find . -type d \( -name "sit*" -o -name "uat*" \)); do echo "source_up\nexport AWS_PROFILE=cpp-$(basename $d)" > ${d}/.envrc; done
for d in $(find . -type d \( -name "sit*" -o -name "uat*" \)); do direnv allow $d; done
for d in $(find . -type d -name "prod*"); do echo "source_up\nexport AWS_PROFILE=cpp-$(basename $d)-ro" > ${d}/.envrc; done
for d in $(find . -type d -name "prod*"); do direnv allow $d; done
#+end_src
