customCommands:
  - key: "W" # see: https://github.com/jesseduffield/lazygit/issues/1984#issuecomment-1249827818
    prompts:
      - type: "input"
        title: "Commit"
        initialValue: ""
    command: git commit -m "{{index .PromptResponses 0}}" --no-verify
    context: "global"
    subprocess: true
gui:
  showBottomLine: true
  showIcons: true
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
git:
  paging:
    colorArg: always
    pager: delta --paging=never
  parseEmoji: true
os:
  edit: 'lvim {{filename}}'
  editAtLine: 'lvim +{{line}} {{filename}}'
  editAtLineAndWait: 'lvim --remote-wait +{{line}} {{filename}}'
  editInTerminal: true
promptToReturnFromSubprocess: false
