customCommands:
  - key: "W" # see: https://github.com/jesseduffield/lazygit/issues/1984#issuecomment-1249827818
    prompts:
      - type: "input"
        title: "Commit"
        initialValue: ""
    command: git commit -m "{{index .PromptResponses 0}}" --no-verify
    context: "global"
    subprocess: true
  - key: "C"
    command: |
      TRUNK=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p'); git branch --merged $TRUNK | grep -v '^[ *]*'$TRUNK'$' | xargs -r git branch -d
    context: "localBranches"
    description: "(C)lean / prune local branches that have been merged to trunk."
    loadingText: "Pruning merged..."
  - key: "G"
    command: |
      git fetch -p && for branch in $(git for-each-ref --format '%(refname) %(upstream:track)' refs/heads | awk '$2 == "[gone]" {sub("refs/heads/", "", $1); print $1}'); do git branch -D $branch; done
    context: "localBranches"
    description: "Prune local branches no longer on its remote; (G)one."
    loadingText: "Pruning gone..."
  - key: "C"
    command: "git remote prune {{.SelectedRemote.Name}}"
    context: "remotes"
    description: "(C)lean / prune deleted remote branches."
    loadingText: "Pruning remote..."
gui:
  enlargedSideViewLocation: top
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 3
  nerdFontsVersion: "3"
  showBottomLine: false
  showCommandLog: false
  showFileTree: false
  theme:
    selectedLineBgColor: ["#24283b"]
    selectedRangeBgColor: ["#24283b"]
  timeFormat: "2006-01-02"
git:
  paging:
    colorArg: always
    pager: delta --paging=never --dark
  parseEmoji: true
notARepository: quit
os:
  edit: "$EDITOR {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: "nvim --remote-wait +{{line}} {{filename}}"
  editInTerminal: true
promptToReturnFromSubprocess: false
services:
  "gitlab.tech.dnb.no:2222": "gitlab:gitlab.tech.dnb.no"
