customCommands:
  - key: "W" # see: https://github.com/jesseduffield/lazygit/issues/1984#issuecomment-1249827818
    prompts:
      - type: "input"
        title: "Commit"
        initialValue: ""
    command: git commit -m "{{index .PromptResponses 0}}" --no-verify
    context: "global"
    output: terminal
  - key: "C"
    command: git prune-merged
    context: "localBranches"
    description: "(C)lean / prune local branches that have been merged to trunk."
    loadingText: "Pruning merged..."
  - key: "G"
    command: git prune-gone
    context: "localBranches"
    description: "Prune local branches no longer on its remote; (G)one."
    loadingText: "Pruning gone..."
  - key: "C"
    command: "git remote prune {{.SelectedRemote.Name}}"
    context: "remotes"
    description: "(C)lean / prune deleted remote branches."
    loadingText: "Pruning remote..."
  - key: "<c-r>"
    description: "Push to a specific remote repository"
    context: "global"
    loadingText: "Pushing ..."
    prompts:
      - type: "menuFromCommand"
        title: "Which remote repository to push to?"
        command: bash -c "git remote --verbose | grep '/.* (push)'"
        filter: '(?P<remote>.*)\s+(?P<url>.*) \(push\)'
        valueFormat: "{{ .remote }}"
        labelFormat: "{{ .remote | bold | cyan }} {{ .url }}"
      - type: "menu"
        title: "How to push?"
        options:
          - value: "push"
          - value: "push --force-with-lease"
          - value: "push --force"
    command: "git {{index .PromptResponses 1}} {{index .PromptResponses 0}}"
gui:
  enlargedSideViewLocation: top
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 3
  filterMode: fuzzy
  nerdFontsVersion: "3"
  scrollHeight: 1
  showBottomLine: false
  showCommandLog: false
  showFileTree: false
  theme:
    selectedLineBgColor: ["#24283b"]
  timeFormat: "2006-01-02"
git:
  paging:
    colorArg: always
    pager: delta --paging=never --diff-so-fancy
  parseEmoji: true
notARepository: quit
os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim {{filename}} +{{line}}"
promptToReturnFromSubprocess: false
services:
  "dnb.ghe.com": "github:dnb.ghe.com"
  "gitlab.tech.dnb.no:2222": "gitlab:gitlab.tech.dnb.no"
