ctrl_n_shortcuts = true
enter_accept = true
inline_height = 10
invert = true
keymap_mode = "vim-insert"
show_help = false
show_numeric_shortcuts = false
show_preview = false
show_tabs = false
workspaces = true

[theme]
name = "catppuccin-frappe-lavender"
# name = "catppuccin-latte-peach"

[ui]
columns = ["command"]
