[theme.palette]
background = "#303446"
foreground = "#c6d0f5"
selection_background = "#414559"
selection_foreground = "#c6d0f5"
black = "#414559"
blue = "#8caaee"
cyan = "#81c8be"
green = "#a6d189"
magenta = "#ca9ee6"
red = "#e78284"
white = "#949cbb"
yellow = "#e5c890"
light_black = "#51576d"
light_white = "#b5bfe2"
light_red = "#ea999c"
light_magenta = "#f4b8e4"
light_green = "#a6d189"
light_cyan = "#99d1db"
light_blue = "#85c1dc"
light_yellow = "#ef9f76"

[theme.component_style]

title_bar = { front = "#949cbb", back = "#414559", effect = "bold" }

current_story_tag = { front = "#c6d0f5", back = "#51576d", effect = "bold" }
matched_highlight = { front = "#414559", back = "#a6d189" }
metadata = { front = "#949cbb" }
username = { effect = "bold" }
loading_bar = { front = "#ef9f76", back = "#303446" }
header = { front = "#414559", effect = "bold" }
quote = { front = "#c6d0f5" }
italic = { effect = "italic" }
bold = { effect = "bold" }
single_code_block = { back = "#51576d", front = "#c6d0f5" }
multiline_code_block = { front = "#51576d", effect = "bold" }
link = { front = "#81c8be" }
link_id = { front = "#414559", back = "#e5c890" }
ask_hn = { front = "#e78284", effect = "bold" }
tell_hn = { front = "#e5c890", effect = "bold" }
show_hn = { front = "#8caaee", effect = "bold" }
launch_hn = { front = "#a6d189", effect = "bold" }
