# yaml-language-server: $schema=https://gh-dash.dev/schema.json

keybindings:
  prs:
    - key: T
      command: gh enhance -R {{.RepoName}} {{.PrNumber}}

pager:
  diff: delta --paging always --diff-so-fancy

theme:
  colors:
    text:
      primary: "#c6d0f5"
      secondary: "#babbf1"
      inverted: "#232634"
      faint: "#b5bfe2"
      warning: "#e5c890"
      success: "#a6d189"
      error: "#e78284"
    background:
      selected: "#414559"
    border:
      primary: "#babbf1"
      secondary: "#51576d"
      faint: "#414559"
