return {
  {
    "folke/which-key.nvim",
    event = "VeryLazy",
    opts = function()
      local mi = require("mini.icons")
      return {
        icons = {
          rules = {
            { pattern = "close", icon = "󱄊 ", color = "red" },
            { pattern = "diff", cat = "filetype", name = "git" },
            { pattern = "explore", icon = "󰮗 ", color = "cyan" },
            { pattern = "grep", icon = " " },
            { pattern = "harpoon", icon = "󰛢 ", color = "yellow" },
            { pattern = "key", icon = " ", color = "orange" },
            { pattern = "lua", cat = "filetype", name = "lua" },
            { pattern = "obsidian", cat = "filetype", name = "markdown", color = "purple" },
            { pattern = "split", icon = " " },
            { pattern = "spoin", icon = " " },
          },
          separator = "│",
        },
        layout = {
          align = "center",
          spacing = 4,
        },
        preset = "helix",
        show_help = false,
        spec = {
          { "<leader>a", group = "ai", icon = { icon = "󰚩 " } },
          { "<leader>f", group = "file", icon = mi.get("default", "file") },
          { "<leader><tab>", group = "tab" },
          { "<leader>b", group = "buffer" },
          { "<leader>c", group = "code" },
          { "<leader>d", group = "debug" },
          { "<leader>dP", group = "python", icon = { cat = "filetype", name = "python" } },
          { "<leader>f", group = "file" },
          { mode = { "n", "v" }, "<leader>g", group = "git" },
          { "<leader>gd", group = "diffview", icon = { cat = "filetype", name = "git" } },
          { mode = { "n", "v" }, "<leader>gl", group = "link", icon = { cat = "filetype", name = "git" } },
          { "<leader>h", group = "help", icon = { color = "azure", cat = "filetype", name = "help" } },
          { "<leader>n", group = "notes", icon = { color = "purple", cat = "filetype", name = "markdown" } },
          { "<leader>nj", group = "journal", icon = { color = "purple", cat = "filetype", name = "markdown" } },
          { mode = { "n", "v" }, "<leader>nl", group = "link", icon = { color = "purple", cat = "filetype", name = "markdown" } },
          { "<leader>nw", group = "workspace", icon = { color = "purple", cat = "filetype", name = "markdown" } },
          { "<leader>N", group = "neorg", icon = { color = "orange", cat = "filetype", icon = " " } },
          { "<leader>Nj", group = "journal", icon = { color = "orange", cat = "filetype", icon = " " } },
          { "<leader>p", group = "project", icon = { icon = " " } },
          { "<leader>s", group = "search" },
          { "<leader>sn", group = "noice" },
          { "<leader>st", group = "todo", icon = { icon = " " } },
          { "<leader>u", group = "toggle" },
          { "<leader>w", group = "window" },
          { "<localleader>m", group = "mark" },
        },
        win = {
          height = { max = 44 },
          padding = { 1, 3 },
          title_pos = "center",
          width = { min = 26 },
        },
      }
    end,
  },
  {
    "ThePrimeagen/harpoon",
    dependencies = { { "nvim-lua/plenary.nvim" } },
    config = function() require("telescope").load_extension("harpoon") end,
    keys = {
      { "<leader>f1", function() require("harpoon.ui").nav_file(1) end, desc = "harpoon file 1" },
      { "<leader>f2", function() require("harpoon.ui").nav_file(2) end, desc = "harpoon file 2" },
      { "<leader>f3", function() require("harpoon.ui").nav_file(3) end, desc = "harpoon file 3" },
      { "<leader>f4", function() require("harpoon.ui").nav_file(4) end, desc = "harpoon file 4" },
      { "<leader>f5", function() require("harpoon.ui").nav_file(5) end, desc = "harpoon file 5" },
      { "<leader>f6", function() require("harpoon.ui").nav_file(6) end, desc = "harpoon file 6" },
      { "<leader>f7", function() require("harpoon.ui").nav_file(7) end, desc = "harpoon file 7" },
      { "<leader>f8", function() require("harpoon.ui").nav_file(8) end, desc = "harpoon file 8" },
      { "<leader>f9", function() require("harpoon.ui").nav_file(9) end, desc = "harpoon file 9" },
      { "<leader>fl", function() require("harpoon.ui").toggle_quick_menu() end, desc = "harpoon list" },
      { "<leader>fm", function() require("harpoon.mark").add_file() end, desc = "harpoon mark" },
      { "<leader>fn", function() require("harpoon.ui").nav_next() end, desc = "harpoon next" },
      { "<leader>fp", function() require("harpoon.ui").nav_prev() end, desc = "harpoon prev" },
      { "<c-1>", function() require("harpoon.ui").nav_file(1) end, mode = { "i", "n" }, desc = "harpoon file 1" },
      { "<c-2>", function() require("harpoon.ui").nav_file(2) end, mode = { "i", "n" }, desc = "harpoon file 2" },
      { "<c-3>", function() require("harpoon.ui").nav_file(3) end, mode = { "i", "n" }, desc = "harpoon file 3" },
      { "<c-4>", function() require("harpoon.ui").nav_file(4) end, mode = { "i", "n" }, desc = "harpoon file 4" },
      { "<c-5>", function() require("harpoon.ui").nav_file(5) end, mode = { "i", "n" }, desc = "harpoon file 5" },
      { "<c-6>", function() require("harpoon.ui").nav_file(6) end, mode = { "i", "n" }, desc = "harpoon file 6" },
      { "<c-7>", function() require("harpoon.ui").nav_file(7) end, mode = { "i", "n" }, desc = "harpoon file 7" },
      { "<c-8>", function() require("harpoon.ui").nav_file(8) end, mode = { "i", "n" }, desc = "harpoon file 8" },
      { "<c-9>", function() require("harpoon.ui").nav_file(9) end, mode = { "i", "n" }, desc = "harpoon file 9" },
      { "<c-,>", function() require("harpoon.ui").toggle_quick_menu() end, mode = { "i", "n" }, desc = "harpoon list" },
      { "]f", function() require("harpoon.ui").nav_next() end, desc = "harpoon next" },
      { "[f", function() require("harpoon.ui").nav_prev() end, desc = "harpoon prev" },
    },
  },
  {
    "voldikss/vim-browser-search",
    config = function()
      -- Better to update the defaults since they aren't removed otherwise.
      -- vim.g.browser_search_engines = {}
      vim.g.browser_search_builtin_engines = {
        duckduckgo = "https://duckduckgo.com/?q=%s",
        github = "https://github.com/search?q=%s",
        gitlab = "https://gitlab.com/search?search=%s",
        google = "https://google.com/search?q=%s",
        mdn = "https://developer.mozilla.org/en-US/search?q=%s",
        scholar = "https://scholar.google.com/scholar?q=%s",
        stackoverflow = "https://stackoverflow.com/search?q=%s",
        translate = "https://translate.google.com/?sl=auto&tl=en&text=%s",
        wikipedia = "https://en.wikipedia.org/wiki/%s",
        youtube = "https://www.youtube.com/results?search_query=%s&page=&utm_source=opensearch",
      }
      vim.g.browser_search_default_engine = "duckduckgo"
    end,
    event = "VeryLazy",
    keys = {
      -- Command BrowserSearch always searches one less than index given.
      { "<leader>sb", ":BrowserSearch<space>", desc = "browser" },
      { "<c-k>", "<Plug>SearchNormal", desc = "browser search" },
      { "<c-k>", "<Plug>SearchVisual", desc = "browser search", mode = "v" },
    },
  },
}
