provider = "gitlab"
api_url = "https://gitlab.tech.dnb.no"
token_command = "security find-generic-password -w -s gitlab.tech.dnb.no -a adam.lawrence.sherwood@dnb.no"
root = "."

[filters]
owner = true
groups = [
  "dnb/cbcommon",
  "dnb/ccp",
  "dnb/cppshasl",
  "dnb/cptf",
  "dnb/dcf",
  "dnb/dnb-common",
]
