custom_cursor_colors = true
import = ["~/.config/alacritty/tokyonight.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 20.0

[font.bold]
family = "ZedMono NF Light Obl"

[font.normal]
family = "ZedMono NF Light Obl"

[scrolling]
history = 10000

[window]
decorations = "none"
dynamic_title = false
startup_mode = "Fullscreen"

[window.dimensions]
columns = 120
lines = 48

[window.padding]
x = 20
y = 20
